[package]
name = "metrics_lockfree_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "metrics_lockfree_macros"

[dependencies]
heck = "0.5"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features  = ["parsing"] }
metrics_lockfree = { path = "../metrics_lockfree/" } 
